services:
  research-agent:
    container_name: Research-Agent
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      # API Keys
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # Server Configuration
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=${RELOAD:-False}
      - DEBUG=${DEBUG:-False}
      # Session Management
      - SESSION_EXPIRY_HOURS=${SESSION_EXPIRY_HOURS:-24}
      # Literature Search Settings
      - DEFAULT_SEARCH_LIMIT=${DEFAULT_SEARCH_LIMIT:-10}
      - MAX_SEARCH_LIMIT=${MAX_SEARCH_LIMIT:-50}
    env_file:
      - .env
